### ISSUE TITLE
You can use the main HTML tag here

### ISSUE THREAD

**Issue by kostasx** [irinakalman/FrontEndCourseExercises#2]
https://github.com/irinakalman/FrontEndCourseExercises/blob/3e4eb1076926b68da65591ac4f32b0e67b05430e/The%20Front%20End/HTML%20%20CSS%20Basics/table_styled.html#L62

Instead of a div with class main, you can use the <main> tag. Avoid using div as much as possible and prefer semantic HTML elements. You can target the element via the `main` tag selector in CSS.

**Comment by irinakalman** [comment]
> https://github.com/irinakalman/FrontEndCourseExercises/blob/3e4eb1076926b68da65591ac4f32b0e67b05430e/The%20Front%20End/HTML%20%20CSS%20Basics/table_styled.html#L62
> 
> Instead of a div with class main, you can use the
> 
> tag. Avoid using div as much as possible and prefer semantic HTML elements. You can target the element via the `main` tag selector in CSS.

Alright, thank you for the comments! Can I edit it here remotely? or I need to edit it on my laptop and then push again?

**Comment by kostasx** [comment]
If you haven't done this already, you can make the changes locally, add, commit and push.

**Comment by irinakalman** [comment]
Yes, I have done that. Thank you for your comments, i hope i have fixed everything correctly.
